name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run type checking
      run: npm run lint

    - name: Build package
      run: npm run build

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Update package.json version
      run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        body: |
          **LLM Credit SDK v${{ steps.version.outputs.VERSION }}**
          
          ## What's Changed
          - See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details
          
          ## Installation
          ```bash
          npm install @tokenix/llm-credit-sdk
          ```
          
          ## Quick Start
          ```typescript
          import { LLMCreditSDK, openAIChatExtractor } from '@tokenix/llm-credit-sdk';
          
          const sdk = new LLMCreditSDK();
          // See README for full usage examples
          ```
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }} 